#!/bin/bash

season3Ext=(aad abd abl ach acp acv ads aeminfo ajp ala ali alp aml amr ams amsd aps arc ari arj ars aser atk bap beminfo bjt blow_save btb caip ccd ccp cda cdarate cdl cdl_pawn cdrr cdrt cecp cee chant cip ckc cks col counter_Adj cpe cpl cqi cql cqr crs csd csi csl ctc cuex damage_save damage_spAdj dds dgm dja dja_pawn dme dmi dmt dscp dsd dse dsl dsp dtt dvw dwm e2d ean ebi_sv ebs ect edt edt_color_def edt_mod_pal edt_muscle edt_pset_pal edt_tex_pal edt_voice_pal edv eef efl efs eir ele eli em_scr_adj ema emg emparam eoc epi epl epp epv equip_preset equr era eroSmall_info eroSuper_info ero_addTime esa esh esi esl esn esp est evd evl evlst evp evsi evtr ewk ewp f2p faa fad fal fat_adjust fbik_human2 fedt_jntpreset fmd fmi fnd fng fni fnl fsm gat gfd gii gmd gmp gpl grs grw gui head_ctrl hmcs hmeparam hmeq hmpre hni ik ikctrl ipa ir_adj ir_adj_pl jbi jcp jex2 jlt2 jmc jmp jnt_info jnt_order jobbase jtq kcm kcp kctt lae lai lcd lcm lcp ldp leg_ctrl lmt lop lot lrc lup map mcm mcw mdr mgcc mmc mod mot_filter motparam mra mrl msd mser msl mss nav nci ncs ndp ned nem nll nmm nmp nms nsd nsp nvc oIp occ oce ofi olp omk ompe ompp opp osp paa pam pao pas paw pc_ptkc peg pen pep phs planet plt plu png ppr ppt pqi pqt prs ps_info psi pssc pssl ptc ptc ptk push_rate qhd qmi qsq qst qtd rac rag rbd rds reg_ersion reg_info repgmdlist revr rsl rtex rwr sal sal2 sar sbb sbc sbkr sbv sca scc sce sck scl_change scpx scsr sdl sdsr sdt sg_tbl shake_ctrl shi shl sit sja sky slm slt smc smp sms smxr sn2 sot spg_tbl spl spo sri sri2 srqr ssqr sta stc sti stp stqr sts swm tcm tco tde tdm tex tlt tmc tmo tqg txt ujp vib wal wallmaria wcrt wep wp2 wpn_ofs wpt wrt wsi wta wte wtf wtl xsew zip zon)

for ext in ${season3Ext[@]}; do
	echo "${ext}," >>season3headers.csv
	find /d/DDON_03040008/nativePC/rom -type f -name "*.${ext}" -print -exec xxd -l 4 {} \; -quit | tee -a season3headers.csv
	echo -e "\n" >>season3headers.csv
done
