:toc:
:toc-placement!:
:toclevels: 5

= Wikis and other resources

toc::[]

== Original links

* https://web.archive.org/web/20150801022451/http://www.dd-on.jp/test/beta/
* https://web.archive.org/web/20161116172555/http://www.dd-on.jp/pc/index.html
* https://web.archive.org/web/20170711050027/https://members.dd-on.jp/shop/payment/course/9
* https://web.archive.org/web/20190512205627mp_/https://members.dd-on.jp/lestanianews/item/weapon/handsword
* https://web.archive.org/web/20171108223930/https://members.dd-on.jp/info/special/mandragora/top.html
* https://web.archive.org/web/20190507052523/https://members.dd-on.jp/manual/
* https://web.archive.org/web/20191128061715/http://www.dd-on.jp/
* https://web.archive.org/web/20191023233834/https://members.dd-on.jp/lestanianews/quest/list

== Wikis

=== JP

* https://web.archive.org/web/20240725071834/https://wiki.famitsu.com/dd-online/%E7%89%B9%E9%9B%86%E8%A8%98%E4%BA%8B
* https://h1g.jp/dd-on/
* https://wiki3.h1g.jp/dd-on/
* https://donutland.jp/edl/lestips/
* https://dogmaonlineyyy.wiki.fc2.com/
* https://wikiwiki.jp/blacktea/
* https://site-1173478-1301-337.mystrikingly.com/
* https://ddon38.jp/
* https://kagesato.blog.fc2.com/
* https://rilassato.net/ddon/
* https://www.4gamer.net/games/289/G028968/
* https://web.archive.org/web/20250122221256/https://browsegames.net/ddon
* https://www.gamer.ne.jp/game/1000050549/

=== EN

* http://ddon.wikidot.com/
* https://julien-schu.tumblr.com/ddon.html
* http://seiyria.com/ddon-faq/
* https://ddon.miraheze.org/wiki/Main_Page
* https://maxhubnet0x01.github.io/ddon-fan-wiki/

'''

== Google Docs

* DDO KEYS https://docs.google.com/spreadsheets/d/1BmJnQCod2J6Gik1UhLSJPS7Yx_Sg841-H07av8g_Oa0/edit#gid=0
* DDON Skills https://docs.google.com/spreadsheets/d/1MF7PXo1uZnXQyTMNuMUsvRqyf1JiQgikq1f2glR5BWU/edit#gid=221071286
* Monster List https://docs.google.com/spreadsheets/d/1JKhZUgogfrmyz72kQFWhCSsUXZxLTPQDXHMPYGZ5iqE/edit?pref=2&pli=1#gid=1452998901
* LIBRARY https://docs.google.com/spreadsheets/d/1nxolxvOQXNj4naHmPYIG02YgX7isObhkSlX9osuJMcQ/edit?pli=1#gid=0
* Dragons Dogma Online https://docs.google.com/spreadsheets/d/1CyRBbHRRgulwWgmwGNZKUZX4NCqa_pvwpiC9maf1TPw/edit?usp=sharing
* DDON ARC DUMP https://docs.google.com/spreadsheets/d/1fGcHMKRCC9zjrZiixtq5nebu2vmGzVZ3JB0XY-a2cHg/edit?gid=180010749#gid=180010749

== Playthroughs

* https://www.youtube.com/watch?v=jrsd7JbGK6g&list=PLRu0bOg51m--6eVsfOB87JOUlaIEiCLt6
* https://www.youtube.com/@mikamikk466/videos
* https://www.youtube.com/@スザク流星/featured
* https://www.youtube.com/@panpanddondon1378/videos
* https://www.youtube.com/@kuu21/playlists
* https://www.youtube.com/watch?v=-3nAjdk3CA8&list=PLDQPawZAB1t2IMS9tDFQnIhab6MMrQLgY&index=1
* https://www.youtube.com/playlist?list=PLLotc2h0rNhvrp62_IAmIla2w5KlKAkEE
* https://www.youtube.com/watch?v=jrsd7JbGK6g&list=PLRu0bOg51m--6eVsfOB87JOUlaIEiCLt6

=== Specific videos

* Servant's Loungewear recipe unlock via achievement + crafting + change attire of pawn: https://youtu.be/2hQowGg5SiY?si=FuuaVfaY7lLLPFl4&t=167
* Job Emblem: https://www.youtube.com/watch?v=sjUbZ_I3G4I
* 5x course XP dungeon: https://www.youtube.com/watch?v=2xlevOQvASE


==== Crafting

Someone pressed the craft skill analyze button:
* https://youtu.be/UeYUn9NLn7U?si=ojrPqcW5yOc9FKCB&t=507
* https://youtu.be/UeYUn9NLn7U?si=Oso6ylv2_aGkG8v7&t=708
* https://youtu.be/UeYUn9NLn7U?si=A5FDfBx4ha6x_Opx&t=732

Craft support pawn visible (also contains legend pawns):
* https://youtu.be/DnMq4eP38jA?si=CaIKWcl-DH1ErBOF&t=369

Someone pressed the craft product info button (from production status):
* https://youtu.be/SDhlTgm6nYE?si=bb8e88P7-2BCrGgk&t=79

Craft class up UI / promotional exam:
* https://youtu.be/HyAzodGOz6Q?si=ST0HciKbyKGMBLPK&t=5 45-60
* https://youtu.be/M8OMTWqz0J8?si=FbKYbgGmNNHutSPB&t=3 56-60
* https://youtu.be/5P2MA5p6ZZ4?si=IXlO3kMDhus-bkf9&t=8 7->8 


==== Event Codes / Treasure Lots

* Event Code visible in chat + Treasure Lot 1.x: https://youtu.be/ZNwaC1TzaEw?si=_0t8UJEFZJI5mw6t&t=44
* Treasure Lot 2.1: https://www.youtube.com/watch?v=Lyne9CiGmks
* Treasure Lot 2.2: https://www.youtube.com/watch?v=4FqrcBBec3M => Item post shows up: https://youtu.be/4FqrcBBec3M?si=R3w0x8DhS5bYaVg4&t=325
* Treasure Lot 3.3: 
    * https://www.youtube.com/watch?v=odK6nqDJ7T8
    * https://www.youtube.com/watch?v=d5jMW1OW6pA => Box Treasure Lot 3.3: https://www.youtube.com/live/d5jMW1OW6pA?si=_c5mk-zlIsvNcuLk&t=1119
* Large Delivery Event:
    * https://www.youtube.com/live/d5jMW1OW6pA?si=_2Yp4pIQSSN6FE4F&t=1472
    * https://www.youtube.com/live/d5jMW1OW6pA?si=CZsLGMKGSC7sbZZ4&t=2625
* Box Treasure Lot DDON Style: https://www.youtube.com/watch?v=43cas8toGz8

==== BBM

BBM Treasure Chest Opening: ("DDON" "黒呪の迷宮" "装備")

===== BBM Death Marathon:

"If you want to reset the right to acquire all items including the bracelet, you should perform a “Reset Progression and Rewards”.
Reset Progress” is used when a party member drops out of the game and you want to replay the game with the same progress, or when you just want to fight Death and get rare items (commonly known as a ‘death marathon’)."

* Reset 1: https://www.youtube.com/live/9tmd3VJ_iCI?si=d00xfimvnv7SNnGL&t=580
* Reset 2: https://www.youtube.com/live/9tmd3VJ_iCI?si=5twsSbhZwgIrkFpf&t=1646
* Reset 3: https://www.youtube.com/live/9tmd3VJ_iCI?si=7uBkzg7T0v83LJtB&t=2810 

===== High Scepter Maze 1 Normal Treasure Map 1
* https://youtu.be/zDOJ8l3pWeI?si=U15J8DMabz0S-WHf&t=330 => Weapon 1 IR6 Lv30
* https://youtu.be/zDOJ8l3pWeI?si=fDBz-tn0dWDDdRK9&t=351 => Armor IR3 Lv13 2 star, Armor IR3 Lv12 4 star
* https://youtu.be/zDOJ8l3pWeI?si=1msUEUyMCT7cu_ec&t=396 => Armor IR2 Lv7
* https://youtu.be/zDOJ8l3pWeI?si=lgEWEdIP_zUQoFUB&t=412 => Weapon 1 IR6 Lv30, Armor IR3 Lv12
* https://youtu.be/zDOJ8l3pWeI?si=IDcmT6Jv8sucONx_&t=427 => Consumables
* https://youtu.be/zDOJ8l3pWeI?si=9qN4_RAc-QA9bfGM&t=462 => Consumables, Armor IR3 Lv12 3 star, Armor IR3 * Lv12 1 star
* https://youtu.be/zDOJ8l3pWeI?si=QErir0mwwIUAyGqv&t=493 => (checks item bag)
* https://youtu.be/zDOJ8l3pWeI?si=dRFk8vnkBEAuvuOg&t=616 => Consumables
* https://youtu.be/zDOJ8l3pWeI?si=_k-DwLcckKM3CqX8&t=635 => Consumables, Armor IR2 Lv9 3 star, Armor IR2 Lv7 * 2 star, Armor IR3 Lv12 3 star
* https://youtu.be/zDOJ8l3pWeI?si=cHHdMW2UsPF2B-Cn&t=664 => Consumables, Armor IR3 Lv13 1star, Armor IR3 * Lv12 3star, Armor IR3 Lv11
* https://youtu.be/zDOJ8l3pWeI?si=s8c7eCkJsqfRJBzm&t=678 => (checks item bag)

===== High Scepter Maze 1 Normal Treasure Map 2
* https://youtu.be/zDOJ8l3pWeI?si=_2KJgxh6bxsV74na&t=765 => Consumables, Armor IRX LvX 3star, Armor IR4 Lv16, Armor IRX LvX 3star
* https://youtu.be/zDOJ8l3pWeI?si=l5-7u4JGxmiIAjEJ&t=798 => Consumable, Weapon 1 IR6 Lv30
* https://youtu.be/zDOJ8l3pWeI?si=LCbXNpj0gIqUpwyO&t=804 => Armor IR4 Lv18, Weapon 1 IR6 Lv30
* https://youtu.be/zDOJ8l3pWeI?si=PogeoCAbjaQkdvnq&t=878 => Consumables, Armor IRX LvX 1star, Armor IRX LvX 3star, Armor IRX LvX 1star
* https://youtu.be/zDOJ8l3pWeI?si=ZeJweyQ49kcyt1Ct&t=1319 => Consumables, 4x Armor ~IR4

===== High Scepter Maze 1 Boss Treasure:
* https://youtu.be/zDOJ8l3pWeI?si=mvOVQXHp8bidn2Bn&t=1278 => Weapon 1 IR6 Lv30
* https://youtu.be/zDOJ8l3pWeI?si=RFRc_SQ31ij811pq&t=1281 => Bracelet IR50 Lv1
* End of Maze 1 Map 2: https://youtu.be/zDOJ8l3pWeI?si=osrSr9T5OUzzruzl&t=1351 = (checks item bag)


==== Mandragoras

* 3.2 https://www.youtube.com/watch?v=HueZ2gCklBo
* 3.4 https://www.youtube.com/watch?v=j6eJjfvagTc 

==== EMs

* EM1 Runs: https://www.youtube.com/results?search_query=DDON+地下墓場の誘い
* Party: https://www.youtube.com/watch?v=QonQekR_Kvs 
* Solo 60: https://www.nicozon.net/player.html?video_id=sm28461081
* Quick: https://www.youtube.com/watch?v=JotR8tp9hrw
* 8 Arisen in a 'Grand Mission': https://www.youtube.com/watch?v=9Y_blEk6JHM&t=314s

== Repositories

=== Item & monster placing
* https://github.com/alborrajo/DDOn-Tools

=== Launchers
* https://github.com/D00MK1D/DDON-Launcher
* https://github.com/Najelith/ddo_launcher

=== Server
* https://github.com/sebastian-heinz/Arrowgene.DragonsDogmaOnline

=== Client and packet reverse engineering
* https://github.com/sebastian-heinz/DDON_RE
* https://github.com/ddon-research/ddon-data
* https://github.com/ddon-research/ddon-extractor

=== Packet key bruteforcing
* https://github.com/ddon-research/ddon-bruteforcer-gui
* https://github.com/sebastian-heinz/ddon_common_key_bruteforce

=== Translation
* https://github.com/riftcrystal/DDON-Translation
* https://github.com/Sapphiratelaemara/DDON-translation

=== Backing up old wikis

Currently playing around with various settings and tools to back up pages beyond the Wayback Machine / Internet Archive, as it doesn't properly do recursive back ups by default (only does the initial outgoing links it finds on the first URL you provide).

I ended up with Browsertrix and like how this is open source and neatly packages a website as a standalone thing (they use the same standardized web archive format IA uses), completely rewriting all links and resources with minimal effort: https://crawler.docs.browsertrix.com/user-guide/

Replay WACZ via
Web client: https://replayweb.page/
Desktop client: https://github.com/webrecorder/replayweb.page/releases/tag/v2.2.5):

WARC extraction to get to HTML pages:
https://github.com/chfoo/warcat-rs
https://warcat-rs.readthedocs.io/en/latest/usage_examples.html#extract-everything
Extract the WACZ via 7-zip or unzip then use warcat to extract the warc.gz file in the archive folder:
warcat extract --input "archive\rec-06e7f4f19938-20250122204822175-0.warc.gz"

Site: https://wikiwiki.jp/blacktea/
WACZ: https://drive.google.com/file/d/1VGy-iiM2dKIyjRnmaqMtqQEaItwI_ika/view?usp=sharing
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection wikiwiki-blacktea --sitemap https://wikiwiki.jp/blacktea/sitemap.txt --url https://wikiwiki.jp/blacktea/ --scopeExcludeRx "wikiwiki.jp/blacktea/\?.*" 
The reason I decided against wget and other alternatives: I've fiddled around with various wget settings or python-based scripts/libraries etc., but ultimately I couldn't get them to properly parse either sitemaps or they tend to go "too far" or "not far enough" as far as mirroring all the resources and then fail to rewrite the resources, requiring you to host complex web servers with rewrite modules or manually fix links etc. But for the record I was playing around with these commands:

Example:
wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0" --local-encoding=UTF-8 --wait=1 --random-wait --force-directories --adjust-extension --mirror --page-requisites --span-hosts --restrict-file-names=windows --convert-links -e robots=off --no-parent -D dragonsdogma.com https://www.dragonsdogma.com/
 
I intend to create backups for the known useful wikis we have found so far that are at risk to be lost.
Site: https://seiyria.com/ddon-faq/ 
WACZ: https://drive.google.com/file/d/1jIs-1n5GVZO78kx6TUfiZfuqKICQ7sW7/view?usp=sharing
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection seiyria-ddon-faq --url https://seiyria.com/ddon-faq/ --scopeIncludeRx "seiyria.com/ddon-.*" 

Sam — 23/01/2025 07:37
Site: https://site-1173478-1301-337.mystrikingly.com/ 
WACZ: https://drive.google.com/file/d/1gV3tJ9FDNy9WKH9ggkdU54Py1hljUCDk/view?usp=sharing
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection mystrikingly-ddon --sitemap https://site-1173478-1301-337.mystrikingly.com/sitemap.xml --url https://site-1173478-1301-337.mystrikingly.com/ --scopeIncludeRx "site\-1173478\-1301\-337\.(my)?strikingly\.com\/" 
Site: http://ddon.wikidot.com/
WACZ: https://drive.google.com/file/d/1fE5wzJjY30TLoxQtOl5AICJWuCyg3-0K/view?usp=sharing
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection wikidot --sitemap http://ddon.wikidot.com/sitemap.xml --url http://ddon.wikidot.com/ 

Sam — 25/01/2025 15:12
Site: https://donutland.jp/edl/lestips/
WACZ: https://drive.google.com/file/d/1xMPRtiCr3Mxu5sgxL0oZD98SFhc0zLDB/view?usp=sharing
Notes: The web replayer (desktop version doesn't work at all) has some issues with the font, so you have to click on the URLs once, navigate back and then it should load properly.
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection donutland-lestips --url https://donutland.jp/edl/lestips/ 

Sam — 27/01/2025 12:41
Site: https://h1g.jp/dd-on/
WACZ: https://drive.google.com/file/d/15wRaR8aXdE2GI7FVmWDpL_KkX_ZltCvj/view?usp=sharing
Notes: 7GB in size, web player won't load it, desktop client works fine.
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection h1g-dd-on --url https://h1g.jp/dd-on/ --scopeExcludeRx "h1g\.jp\/dd-on\/(\?(cmd|plugin)|.*RecentDeleted)" 

Sam — 28/01/2025 19:37
Site: https://ddon38.jp/
WACZ: https://drive.google.com/file/d/1-GSQsSrkpjhojVQyu7PUwUx_THposWVB/view?usp=sharing
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection ddon38 --sitemap https://ddon38.jp/sitemaps.xml --url https://ddon38.jp/

Sam — 29/01/2025 18:11
Site: https://rilassato.net/category/ddon/
WACZ: https://drive.google.com/file/d/11MGLfpuY3Uw1Ct1VtYZRZ70SCaIEnhgi/view?usp=sharing
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection rilassato --sitemap https://rilassato.net/sitemap.xml --url https://rilassato.net/category/ddon/ --scopeIncludeRx "rilassato\.net\/((category\/ddon\/.*)|((wp|ddon)\/.*))"

Sam — 29/01/2025 18:53
Site: https://www.4gamer.net/games/289/G028968/
WACZ: https://drive.google.com/file/d/1TI6lgIY29792kK5V2ZZfzgBr4PTfDNTP/view?usp=sharing
Note: Their article index/search is some weird PHP mess that the webrecorder managed to capture but it's somewhat unusable, it's easier to use the "Resources" search in the replayer app and filter on "HTML" & "Contains" with "G028968".
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection 4gamer-ddon --url https://www.4gamer.net/games/289/G028968/ --scopeIncludeRx "(module\.)?4gamer\.net\/((games\/289\/G028968\/.*)|((script|js|tags|image|img|css)\/.*))" 

Sam — 30/01/2025 11:25
Site: https://dogmaonlineyyy.wiki.fc2.com/
WACZ: https://drive.google.com/file/d/1r_jE7rF6IacRgHx1q0e_6mHigtNC_RCw/view?usp=sharing
Note: This is one of the few wikis that normally requires a JP VPN to visit/backup.
Command: docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --waitUntil networkidle0 --extraHops 0 --scopeType prefix --blockAds --generateCDX --generateWACZ --text final-to-warc --collection fc2-dogmaonlineyyy --sitemap https://dogmaonlineyyy.wiki.fc2.com/sitemap.xml --url https://dogmaonlineyyy.wiki.fc2.com/ --scopeExcludeRx "dogmaonlineyyy\.wiki\.fc2\.com\/dd-on\/(\?(cmd|plugin)|.*RecentDeleted)"
