namespace DDOAppMaster.Enum;

public enum QuestContentType
{
	QUEST_CONTENTS_TYPE_UNKNOWN = 0,
	QUEST_CONTENTS_TYPE_HUNTING = 2,
	QUEST_CONTENTS_TYPE_DELIVERY = 1,
	QUEST_CONTENTS_TYPE_PICTURE = 3,
	QUEST_CONTENTS_TYPE_NUM = 4
}
