namespace DDOAppMaster.Enum.Equip;

public enum EquipCategory
{
	EQUIP_CATEGORY_NONE,
	EQUIP_CATEGORY_WEP_MAIN,
	EQUIP_CATEGORY_WEP_SUB,
	EQUIP_CATEGORY_ARMOR_HELM,
	EQUIP_CATEGORY_ARMOR_BODY,
	EQUIP_CATEGORY_WEAR_BODY,
	EQUIP_CATEGORY_ARMOR_ARM,
	EQUIP_CATEGORY_ARMOR_LEG,
	EQUIP_CATEGORY_WEAR_LEG,
	EQUIP_CATEGORY_ACCESORY,
	EQUIP_CATEGORY_JEWELRY,
	EQUIP_CATEGORY_LANTERN,
	EQUIP_CATEGORY_COSTUME,
	EQUIP_CATEGORY_UNIFORM,
	EQUIP_CATEGORY_FULLSUIT,
	EQUIP_CATEGORY_MAX
}
