namespace DDOAppMaster.Enum.Craft;

public enum CraftSkillType
{
	PAWN_CRAFT_SKILL_NONE = 0,
	PAWN_CRAFT_SKILL_SPEEDUP = 1,
	PAWN_CRAFT_SKILL_GRADEUP = 2,
	PAWN_CRAFT_SKILL_QUALITYUP = 3,
	PAWN_CRAFT_SKILL_ITEMNUM = 4,
	PAWN_CRAFT_SKILL_COSTDOWN = 5,
	PAWN_CRAFT_SKILL_PERFECT_ITEMNUM = 6,
	PAWN_CRAFT_SKILL_PERFECT_QUALITYUP = 7,
	PAWN_CRAFT_SKILL_NO_LIMIT_ASSIST_COSTDOWN = 8,
	PAWN_CRAFT_SKILL_USE_SP_SKILL_TABLE = 9,
	PAWN_CRAFT_SKILL_RARE_ITEMNUM_BONUS = 10,
	PAWN_CRAFT_SKILL_MAX = 11,
	PAWN_CRAFT_SKILL_NUM = 10
}
