namespace DDOAppMaster.Enum.OnlineStatus;

public enum E_ONLINE_STATUS
{
	ONLINE_STATUS_NONE,
	ONLINE_STATUS_ONLINE,
	ONLINE_STATUS_OFFLINE,
	ONLINE_STATUS_LEAVING,
	ONLINE_STATUS_BUSY,
	ONLINE_STATUS_ENTRY_BOARD,
	ONLINE_STATUS_QUICK_MATCH,
	ONLINE_STATUS_EVENT,
	ONLINE_STATUS_CONTENTS,
	ONLINE_STATUS_PT_LEADER,
	ONLINE_STATUS_PT_MEMBER,
	ONLINE_STATUS_LOST,
	ONLINE_STATUS_SERVER_MOVE,
	ONLINE_STATUS_PT_PAWN,
	ONLINE_STATUS_NUM
}
