namespace Packet;

public enum ItemCategory
{
	ITEM_CATEGORY_NONE = 0,
	ITEM_CATEGORY_TOP = 1,
	ITEM_CATEGORY_USE = 1,
	ITEM_CATEGORY_MATERIAL = 2,
	ITEM_CATEGORY_EQUIP = 3,
	ITEM_CATEGORY_KEY = 4,
	ITEM_CATEGORY_JOB = 5,
	ITEM_CATEGORY_FURNITURE = 6,
	ITEM_CATEGORY_CRAFT_RECIPE = 7,
	ITEM_CATEGORY_PROFILE_BG = 8,
	ITEM_CATEGORY_EDIT_PARTS = 9,
	ITEM_CATEGORY_EMOTION = 10,
	ITEM_CATEGORY_ABILITY = 11,
	ITEM_CATEGORY_PAWN_TALK = 12,
	ITEM_CATEGORY_FIXED_PHRASE = 13,
	ITEM_CATEGORY_CLAN_FURNITURE = 14,
	ITEM_CATEGORY_MAX = 15,
	ITEM_CATEGORY_NUM = 14
}
