namespace Packet;

public enum ServerUID
{
	INVALID = 0,
	EVENT_ACHIEVE_LIST = 100,
	EVENT_ACHIEVE_DETAIL = 101,
	AREA_LIST_AREA_LIST = 200,
	AREA_LIST_SPOT_LIST = 201,
	AREA_LIST_SPOT_DETAIL = 202,
	AREA_LIST_TOP_PAGE = 203,
	AREA_LIST_ENEMY_SEARCH = 204,
	AREA_LIST_ENEMY_SELECT = 205,
	AREA_LIST_ENEMY_LIST = 206,
	AREA_LIST_ITEM_SEARCH = 207,
	AREA_LIST_ITEM_SELECT = 208,
	AREA_LIST_ITEM_LIST = 209,
	LIGHT_QUEST_AREA_LIST = 300,
	LIGHT_QUEST_CLAN_BOARD_LIST_LIST = 301,
	LIGHT_QUEST_LIST = 302,
	LIGHT_QUEST_DETAIL = 303,
	EVENT_PAGE_TOP = 400,
	EVENT_PAGE_WAR_MISSION = 401,
	EVENT_PAGE_WAR_MISSION_RANKING = 402,
	EVENT_PAGE_WAR_MISSION_REWARD = 403
}
